# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentNotice',
            new_name='Tweet',
        ),
    ]
